apps/barbearias/urls.py
from django.urls import path

from .views import ContaReceberCreate, DashboardView, PerfilView, Agenda
from .views import ContaPagarVisualizar, ContaReceberVisualizar
from .views import ServicosList, ClientesList, ProfissionaisList, ProdutosList, EnderecoList
from .views import ContaPagarList, ContaReceberList, FornecedoresList
from .views import ServicosCreate, ClientesCreate, HorarioFuncionamentoCreate, ProfissionaisCreate
from .views import ProdutosCreate, EnderecoCreate, ContaPagarCreate, AgendaHorarioCreate
from .views import ServicosUpdate, ClientesUpdate, HorarioFuncionamentoUpdate, ProfissionaisUpdate
from .views import ProdutoUpdate, BarbeariaUpdate, EnderecoUpdate, ContaPagarUpdate, ContaReceberUpdate
from .views import FornecedorUpdate, AgendaHorarioUpdate
from .views import ServicosDelete, ClientesDelete, ProfissionalDelete, HorarioFuncionamentoDelete
from .views import EnderecoDelete, Produtodelete, ContaPagarDelete, ContaReceberDelete, FornecedorCreate
from .views import AgendaHorarioDelete

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('agenda/', Agenda.as_view(), name='agenda'),

    path('conta-pagar-v/<int:pk>/', ContaPagarVisualizar.as_view(), name='conta_pagarv'),
    path('conta-receber-v/<int:pk>/', ContaReceberVisualizar.as_view(), name='conta_receberv'),

    path('servicos/', ServicosList.as_view(), name='servicos'),
    path('clientes/', ClientesList.as_view(), name='clientes'),
    path('profissionais/', ProfissionaisList.as_view(), name='profissionais'),
    path('produtos/', ProdutosList.as_view(), name='produtos'),
    path('endereco/', EnderecoList.as_view(), name='endereco'),
    path('perfil/', PerfilView.as_view(), name='perfil'),
    path('conta-pagar/', ContaPagarList.as_view(), name='conta_pagar'),
    path('conta-receber/', ContaReceberList.as_view(), name='conta_receber'),
    path('fornecedores/', FornecedoresList.as_view(), name='fornecedores'),

    path('criar-servico/', ServicosCreate.as_view(), name='criar_servico'),
    path('criar-cliente/', ClientesCreate.as_view(), name='criar_cliente'),
    path('criar-profissional/', ProfissionaisCreate.as_view(), name='criar_profissional'),
    path('criar-horario-atendimento/', HorarioFuncionamentoCreate.as_view(), name='criar_horario'), 
    path('criar-produto/', ProdutosCreate.as_view(), name='criar_produto'),
    path('criar-endereco/', EnderecoCreate.as_view(), name='criar_endereco'),
    path('criar-conta-pagar/', ContaPagarCreate.as_view(), name='criar_conta_pagar'),   
    path('criar-conta-receber/', ContaReceberCreate.as_view(), name='criar_conta_receber'),
    path('criar-fornecedor/', FornecedorCreate.as_view(), name='criar_fornecedor'),
    path('criar-horario/', AgendaHorarioCreate.as_view(), name='agenda_horario'),
    
    path('editar-servico/<int:pk>/', ServicosUpdate.as_view(), name='editar_servico'),
    path('editar-cliente/<int:pk>/', ClientesUpdate.as_view(), name='editar_cliente'),
    path('editar-profissional/<int:pk>/', ProfissionaisUpdate.as_view(), name='editar_profissional'),
    path('editar-horario-atendimento/<int:pk>/', HorarioFuncionamentoUpdate.as_view(), name='editar_horario'),
    path('editar-produto/<int:pk>/', ProdutoUpdate.as_view(), name='editar_produto'),
    path('barbearia/<int:pk>/',BarbeariaUpdate.as_view(), name='barbearia'),
    path('editar-endereco/<int:pk>/',EnderecoUpdate.as_view(), name='editar_endereco'),
    path('editar-conta-pagar/<int:pk>/',ContaPagarUpdate.as_view(), name='editar_conta_pagar'),
    path('editar-conta-receber/<int:pk>/',ContaReceberUpdate.as_view(), name='editar_conta_receber'),
    path('editar-fornecedor/<int:pk>/',FornecedorUpdate.as_view(), name='editar_fornecedor'),
    path('editar-agenda/<int:pk>/', AgendaHorarioUpdate.as_view(), name='editar_agenda'),

    path('excluir-servico/<int:pk>/', ServicosDelete.as_view(), name='excluir_servico'),
    path('excluir-cliente/<int:pk>/', ClientesDelete.as_view(), name='excluir_cliente'),
    path('excluir-profissional/<int:pk>/', ProfissionalDelete.as_view(), name='excluir_profissional'),
    path('excluir-horario-atendimento/<int:pk>/', HorarioFuncionamentoDelete.as_view(), name='excluir_horario'),
    path('excluir-endereco/<int:pk>/', EnderecoDelete.as_view(), name='excluir_endereco'),
    path('excluir-produto/<int:pk>/', Produtodelete.as_view(), name='excluir_produto'),
    path('excluir-conta-pagar/<int:pk>/', ContaPagarDelete.as_view(), name='excluir_conta_pagar'),
    path('excluir-conta-receber/<int:pk>/', ContaReceberDelete.as_view(), name='excluir_conta_receber'),
    path('excluir-agenda/<int:pk>/', AgendaHorarioDelete.as_view(), name='excluir_agenda' )
]

barbeiros/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls'), name='index'),
    path('barbearias/', include('apps.barbearias.urls'), name='barbearias'),
    path('usuarios/', include('apps.usuarios.urls'), name='usuarios'),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/barbearias/models.py
from django.db import models
from stdimage import StdImageField
from apps.usuarios.models import CustomUser


class Barbearia(models.Model):
    barbearia = models.CharField(max_length=200, verbose_name='Barbearia')
    nome = models.CharField(max_length=200, verbose_name='Nome')
    telefone = models.CharField(max_length=16, verbose_name='Telefone')
    usuario = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    logo = StdImageField(upload_to='barbearia/logo', variations={
        'thumbnail': {"width": 100, "height": 100, "crop": True},
        'thumb': {"width": 30, "height": 30, "crop": True},
    }, null=True, blank=True)

    class Meta:
        verbose_name = 'Barbearia'
        verbose_name_plural = 'Barbearias'


    def __str__(self):
        return self.barbearia


class Endereco(models.Model):
    global ESTADO_CHOICE

    ESTADO_CHOICE=(
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )

    rua = models.CharField(max_length=150, verbose_name='Rua')
    numero = models.CharField(max_length=5, verbose_name='N°')
    cep = models.CharField(max_length=9, verbose_name='CEP')
    bairro = models.CharField(max_length=100, verbose_name='Bairro')
    cidade = models.CharField(max_length=200, verbose_name='Cidade')
    estado = models.CharField(max_length=2, choices=ESTADO_CHOICE, verbose_name='UF')
    barbearia = models.OneToOneField(Barbearia, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Endereço'
        verbose_name_plural = 'Endereços'
    

    def __str__(self):
        return f'Endereço {self.barbearia}'


class Profissionais(models.Model):
    nome = models.CharField(max_length=100, verbose_name='Nome')
    apelido = models.CharField(max_length=50)
    telefone = models.CharField(max_length=16, verbose_name='Telefone')
    barbearia = models.ForeignKey(Barbearia, on_delete=models.CASCADE)
    imagem = StdImageField(upload_to='profissionais', variations={
        'thumbnail': {"width": 100, "height": 100, "crop": True},
        'thumb': {"width": 30, "height": 30, "crop": True},
    }, null=True, blank=True)
    #cpf = models.CharField(max_length=13, verbose_name='CPF')
    #rua = models.CharField(max_length=150, verbose_name='Rua', blank=True, null=True)
    #numero = models.CharField(max_length=5, verbose_name='N°', blank=True, null=True)
    #cep = models.CharField(max_length=9, verbose_name='CEP', blank=True, null=True)
    #bairro = models.CharField(max_length=100, verbose_name='Bairro', blank=True, null=True)
    #cidade = models.CharField(max_length=200, verbose_name='Cidade', blank=True, null=True)
    #complemento = models.CharField(max_length=100, verbose_name='Complemento', blank=True, null=True)
    #estado = models.CharField(max_length=2, choices=ESTADO_CHOICE, verbose_name='Estado', blank=True, null=True)
    

    class Meta:
        verbose_name = 'Profissional'
        verbose_name_plural = 'Profissionais'
    
    
    def __str__(self):
        return f'{self.nome}'


class Servicos(models.Model):
    TEMPO_CHOICE = (
        ('30', '30 Minutos'),
        ('60', '01 Hora'),
    )
    servicos = models.CharField(max_length=100, help_text='Ex: Barba - Cabelo - Bigode', 
                                verbose_name='Serviço',)
    tempo = models.CharField(max_length=2, choices=TEMPO_CHOICE)
    preco = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Valor')
    barbearia = models.ForeignKey(Barbearia, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'

    
    def __str__(self):
        return self.servicos


class HorarioFuncionamento(models.Model):

    DIAS_CHOICE = (
        ('Segunda a Sexta','Segunda a Sexta'),
        ( 'Segunda a Sábado', 'Segunda a Sábado'),
        ('Segunda-feira','Segunda-feira'), 
        ('Terça-feira','Terça-feira'), 
        ('Quarta-feira', 'Quarta-freira'),
        ('Quinta-feira','Quinta-feira'), 
        ('Sexta-feira','Sexta-feira'), 
        ('Sábado', 'Sábado'), 
        ('Domingo', 'Domingo'),
    )

    dias_da_semana = models.CharField(max_length=16, choices=DIAS_CHOICE)
    horario_inicio = models.CharField(max_length=5 ,verbose_name='Horário Início')
    horario_saida = models.CharField(max_length=5 ,verbose_name='Horário Saída')
    inicio_intervalo = models.CharField(max_length=5 ,verbose_name='Início Intervalo', blank=True, null=True)
    final_intervalo = models.CharField(max_length=5 ,verbose_name='Final Intervalo', blank=True, null=True )
    barbearia = models.ForeignKey(Barbearia, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Horário de Atendimento'
        verbose_name_plural = 'Horários de Atendimento'

    
    def __str__(self):
        return f'Horário Atendimento - {self.barbearia.barbearia}'


class Clientes(models.Model):
    nome = models.CharField(max_length=200, verbose_name='Nome')
    telefone = models.CharField(max_length=16, verbose_name='Telefone')
    barbearia = models.ForeignKey(Barbearia, on_delete=models.PROTECT)
    dataCadastro = models.DateField(auto_created=True, auto_now_add=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    
    def __str__(self):
        return self.nome
    

class Produtos(models.Model):
    nome = models.CharField(max_length=100, verbose_name='Nome')
    preco = models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')
    descricao = models.TextField(max_length=250, verbose_name='Descrição', null=True, blank=True)
    imagem = StdImageField(upload_to='produtos', variations={
        'thumbnail': {"width": 100, "height": 100, "crop": True},
        'thumb': {"width": 30, "height": 30, "crop": True},
    }, null=True, blank=True)
    barbearia = models.ForeignKey(Barbearia, on_delete=models.PROTECT)
   
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    
    def __str__(self):
        return self.nome


class AgendaHorario(models.Model):
    barbearia = models.ForeignKey(Barbearia, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE)
    profissional = models.ForeignKey(Profissionais, on_delete=models.CASCADE)
    servico = models.ForeignKey(Servicos, on_delete=models.CASCADE)
    data = models.DateField(auto_now_add=False, auto_now=False)
    horario = models.TimeField()
    horarioFim = models.TimeField()
    agendado = models.BooleanField(default=True)
    antendido = models.BooleanField(default=False, verbose_name='Atendido')

    class Meta:
        verbose_name = 'Agenda Horario'
        verbose_name_plural = 'Agenda Horarios'

    
    def __str__(self):
        return f'Horário:{self.cliente.nome}'


class ContaPagar(models.Model):
    barbearia = models.ForeignKey(Barbearia, on_delete=models.CASCADE)
    conta = models.CharField(max_length=100)
    valor = models.DecimalField( max_digits=9, decimal_places=2)
    dataVencimento = models.DateField(auto_now=False, auto_now_add=False)
    dataCadastro = models.DateField(auto_created=True, auto_now_add=True)
    infoPago = models.CharField(max_length=10)
    pago = models.BooleanField(default=False)
    vencido = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Conta a Pagar'
        verbose_name_plural = 'Contas a Pagar'


    def __str__(self):
        return f'Conta a Pagar: {self.conta}'


class ContaReceber(models.Model):
    barbearia = models.ForeignKey(Barbearia, on_delete=models.CASCADE)
    conta = models.CharField(max_length=100)
    valor = models.DecimalField(decimal_places=2, max_digits=9)
    dataVencimento = models.DateField(auto_now=False, auto_now_add=False)
    dataCadastro = models.DateField(auto_created=True, auto_now_add=True)
    infoPago = models.CharField(max_length=10)
    pago = models.BooleanField(default=False)
    vencido = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = 'Conta a Receber'
        verbose_name_plural = 'Contas a Receber'

    
    def __str__(self):
        return f'Conta a Receber: {self.conta}'


class Fornecedor(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    celular = models.CharField(max_length=16, blank=True, null=True)
    telefone = models.CharField(max_length=16, blank=True, null=True)
    inscricao = models.CharField(max_length=14, verbose_name='Inscrição Estadual', blank=True, null=True)
    cnpj = models.CharField(max_length=18, blank=True, null=True)
    rua = models.CharField(max_length=150, verbose_name='Rua', blank=True, null=True)
    numero = models.CharField(max_length=5, verbose_name='N°', blank=True, null=True)
    cep = models.CharField(max_length=9, verbose_name='CEP', blank=True, null=True)
    bairro = models.CharField(max_length=100, verbose_name='Bairro', blank=True, null=True)
    cidade = models.CharField(max_length=200, verbose_name='Cidade', blank=True, null=True)
    complemento = models.CharField(max_length=100, verbose_name='Complemento', blank=True, null=True)
    estado = models.CharField(max_length=2, choices=ESTADO_CHOICE, verbose_name='Estado', blank=True, null=True)

apps/barbearias/templates/form_criar/criar_clientes.html
{% load static %}

<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">{{ titulo }}</h2>
    </div>
    <form action="{% url 'criar_cliente' %}" method="POST">
        {% csrf_token %}
        <div class="modal-body">
            {{ form.as_p }}
          </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-info " data-bs-dismiss="modal">Voltar</button>
            <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
        </div>
    </form>
  </div>
</div>


{% block script %}

<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>

    $(document).ready(function(){

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
                spOptions = {
                    onKeyPress: function(val, e, field, options) {
                        field.mask(SPMaskBehavior.apply({}, arguments), options);
                    }
                 };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);

    });

</script>
    
{% endblock %}

apps/barbearias/templates/form_criar/criar_contas_pagar.html
{% load static %}

{% block navs %}

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">{{ titulo }}: {{ object }}</h2>
      </div>
      <form action="{% url 'criar_conta_pagar' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="modal-body">            
            {{ form.as_p }}
          <div class="modal-footer">
              <button type="button" class="btn btn-info " data-bs-dismiss="modal">Voltar</button>
              <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
          </div>
      </form>
    </div>
  </div>

{% endblock %}

apps/barbearias/templates/form_criar/criar_contas_receber.html
{% load static %}

{% block navs %}

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">{{ titulo }}: {{ object }}</h2>
      </div>
      <form action="{% url 'criar_conta_receber' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="modal-body">            
            {{ form.as_p }}
          <div class="modal-footer">
              <button type="button" class="btn btn-info " data-bs-dismiss="modal">Voltar</button>
              <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
          </div>
      </form>
    </div>
  </div>

{% endblock %}

apps/barbearias/templates/form_criar/criar_endereco.html
{% load static %}

<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">{{ titulo }}</h2>
    </div>
    <form action="{% url 'criar_endereco' %}" method="POST">
        {% csrf_token %}
        <div class="modal-body">
          <div class="row mb-2">
              <div class="col-md-4">
                  <p>{{ form.rua.label }}</p>
                  {{ form.rua }}
              </div>
              <div class="col-md-4">
                  <p>{{ form.numero.label }}</p>
                  {{ form.numero }}
              </div>
              <div class="col-md-4">
                  <p>{{ form.cep.label }}</p>
                  {{ form.cep }}
              </div>
          </div>
          <div class="row">
              <div class="col-md-4">
                  <p>{{ form.bairro.label }}</p>
                  {{ form.bairro }}
              </div>
              <div class="col-md-4">
                  <p>{{ form.cidade.label }}</p>
                  {{ form.cidade }}
              </div>
              <div class="col-md-4">
                  <p>{{ form.estado.label }}</p>
                  {{ form.estado }}
              </div>
          </div>
      </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-info " data-bs-dismiss="modal">Voltar</button>
            <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
        </div>
    </form>
  </div>
</div>


{% block script %}

    <script src="{% static 'js/jquery.mask.min.js' %}"></script>

    <script>
        
        $(document).ready(function(){
    
          $('#id_cep').mask('00000-000');
    
        });
    </script>
    
{% endblock%}

apps/barbearias/templates/form_criar/criar_fornecedor.html
{% load static %}

<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">{{ titulo }}</h2>
    </div>
    <form action="{% url 'criar_fornecedor' %}" method="POST">
        {% csrf_token %}
        <div class="modal-body">
          <div class="row mb-2">
            <div class="col-md-6">
                {{ form.nome.label }}
                {{ form.nome }}
            </div>
            <div class="col-md-6">
                {{ form.email.label }}
                {{ form.email }}
            </div>
          </div>
          <div class="row mb-2">
            <div class="col-md-6">
                {{ form.celular.label }}
                {{ form.celular }}
            </div>
            <div class="col-md-6">
                {{ form.telefone.label }}
                {{ form.telefone }}
            </div>
          </div>
          <div class="row mb-2">
            <div class="col-md-6">
                {{ form.inscricao.label }}
                {{ form.inscricao }}
            </div>
            <div class="col-md-6">
                {{ form.cnpj.label }}
                {{ form.cnpj }}
            </div>
          </div>
          <div>
            <h4>Endereço</h4>
          </div>
          <div class="row mb-2">
            <div class="col-md-4">
                {{ form.cep.label }}
                {{ form.cep }}
            </div>
            <div class="col-md-6">
                {{ form.rua.label }}
                {{ form.rua }}
            </div>
            <div class="col-md-2">
                {{ form.numero.label }}
                {{ form.numero }}
            </div>
          </div>
          <div class="row mb-2">
            <div class="col-md-6">
                {{ form.complemento.label }}
                {{ form.complemento }}
            </div>
            <div class="col-md-6">
                {{ form.bairro.label }}
                {{ form.bairro }}
            </div>
          </div>
          <div class="row mb-2">
            <div class="col-md-6">
                {{ form.cidade.label }}
                {{ form.cidade }}
            </div>
            <div class="col-md-6">
                {{ form.estado.label }}
                {{ form.estado }}
            </div>
          </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-info " data-bs-dismiss="modal">Voltar</button>
            <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
        </div>
    </form>
  </div>
</div>

apps/barbearias/templates/form_criar/criar_produtos.html
{% load static %}

{% block navs %}

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">{{ titulo }}: {{ object }}</h2>
      </div>
      <form action="{% url 'criar_produto' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="modal-body">            
            <div class="row d-flex align-items-center ">
                <div class="col ">
                    <p>
                        {{ form.nome.label }}
                        {{ form.nome }}
                    </p>
                    <p>
                        {{ form.preco.label }}
                        {{ form.preco }}
                    </p>
                    <p>
                        {{ form.descricao.label }}
                        {{ form.descricao }}
                    </p>
                </div>
                <div class="col">
                    <div class="row justify-content-center">
                          <img src="{% static 'img/produto_defalt.jpg' %}" alt="" class="rounded-circle w-50"> 
                    </div>
                    <div class="row justify-content-center">
                        {{ form.imagem }}
                    </div>
                </div>          
            </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-info " data-bs-dismiss="modal">Voltar</button>
              <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
          </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block script %}

    <script src="{% static 'js/jquery.mask.min.js' %}"></script>

    <script>
        
        $(document).ready(function(){
    
            $('#id_preco').mask("#.##0,00", {reverse: true});
    
        });
    </script>
    
{% endblock%}

apps/barbearias/templates/form_criar/criar_profissionais.html
{% load static %}

<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">{{ titulo }}</h2>
    </div>
    <form action="{% url 'criar_profissional' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-body">
          <div class="row d-flex align-items-center">
            <div class="col">
                <p>
                    {{ form.nome.label }}
                    {{ form.nome }}
                </p>
                <p>
                    {{ form.apelido.label }}
                    {{ form.apelido }}
                </p>
                <p>
                  {{ form.telefone.label }}
                  {{ form.telefone }}
                </p>
                <p>
                  {{ form.cpf.label }}
                  {{ form.cpf }}
                </p>
            </div>
            <div class="col">
                <div class="row justify-content-center">
                  <img src="{% static 'img/user_defalt.jpg' %}" alt="" class="rounded-circle w-50"> 
                </div>
                <div class="row justify-content-center">
                    {{ form.imagem }}
                </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-info " data-bs-dismiss="modal">Voltar</button>
            <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
        </div>
      </form>
  </div>
</div>


{% block script %}

<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>

    $(document).ready(function(){

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
                spOptions = {
                    onKeyPress: function(val, e, field, options) {
                        field.mask(SPMaskBehavior.apply({}, arguments), options);
                    }
                 };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);

    });

</script>

{% endblock %}

apps/barbearias/templates/form_criar/criar_servico.html
{% load static %}

<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">{{ titulo }}</h2>
    </div>
    <form action="{% url 'criar_servico' %}" method="POST">
        {% csrf_token %}
        <div class="modal-body">
            {% for field in form %}
              <div class="form-group{% if field.errors %} invalid{% endif %}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% for error in field.errors %}
                  <p class="help-block">{{ error }}</p>
                {% endfor %}
              </div>
            {% endfor %}
          </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary " data-bs-dismiss="modal">Voltar</button>
            <button type="submit" class="btn b-save btn-sm" >{{ btn }}</button>
        </div>
    </form>
  </div>
</div>


{% block script %}

    <script src="{% static 'js/jquery.mask.min.js' %}"></script>

    <script>
        
        $(document).ready(function(){
    
            $('#id_preco').mask("00.00", {placeholder: "R$"});
    
        });
    </script>
    
{% endblock%}